#!/bin/bash
#
# Set Heroku config for review app from .env settings

[ $# -ne 2 ] && { echo $0: usage: $0 subapp pr-number; exit 1; }
[ $1 != admin -a $1 != report ] && { echo $0: subapp must be admin or report; exit 1; }

subapp=$1
prnum=$2

# source the .env file, applying $cmd (stripping spaces around '=' sign)
cmd="heroku config:set --app thewhistle-staging-pr-$prnum"
source <(sed -nE "s/[^#]+/$cmd &/ p" .env | sed "s/[ ]*=[ ]*/=/")

# set subapp to $subapp (admin/report)
heroku config:set SUBAPP=$subapp --app thewhistle-staging-pr-$prnum

# ensure NODE_ENV is set to development
heroku config:set NODE_ENV=development --app thewhistle-staging-pr-$prnum

# show config
heroku config --app thewhistle-staging-pr-$prnum
