# JavaScript Node.js CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: echo 127.0.0.1 admin.thewhistle.local report.thewhistle.local twilio.thewhistle.local sms.thewhistle.local | sudo tee -a /etc/hosts
      - run: sudo apt-get install libgconf-2-4
      - run: npm install
      - run: npm test
