# JavaScript Node.js CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo 127.0.0.1 admin.localhost report.localhost | sudo tee -a /etc/hosts
      - run: npm install
      - run: npm test
